version: "3"

services:
    api:
        container_name: text-classification-api
        build: ./src/api
        image: hiseulgi/text-classification-api:latest
        restart: always
        ports:
            - ${API_PORT}:${API_PORT}
        expose:
            - ${API_PORT}
        volumes:
            - ./:/app
            - ./src/api/static/nltk_data:/root/nltk_data
            - /etc/localtime:/etc/localtime:ro
        command: python src/api/main.py

    web:
        container_name: text-classification-web
        build: ./src/web
        image: hiseulgi/text-classification-web:latest
        restart: always
        ports:
            - ${WEB_PORT}:${WEB_PORT}
        expose:
            - ${WEB_PORT}
        volumes:
            - ./:/app
            - /etc/localtime:/etc/localtime:ro
        command: streamlit run src/web/main.py --server.port=${WEB_PORT} --server.address=0.0.0.0
        